sudo: required
services:
  - docker

before_install:
  - docker build -t viriya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  viriya/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  end: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-113611336259"
  bucket_path: "docker-react"
  edge: true
  on:
    branch: master
  access_key_id: $AWS_ID
  secret_access_key:
    secure: $AWS_SECRET
