sudo: required
services:
  - docker

before_install:
  - docker build -t viriya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  viriya/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-113611336259"
  bucket_path: "docker"
  edge: true
  on:
    branch: master
  access_key_id: $AWS_ID
  secret_access_key: $AWS_SECRET
